apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-share
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-share
  template:
    metadata:
      labels:
        app: api-share
    spec:
      containers:
      - name: api-share
        image: r2553/aig-share-page:latest
        ports:
        - containerPort: 4600



---

apiVersion: v1
kind: Service
metadata:
  name: api-share-service
spec:
  selector:
    app: api-share
  ports:
    - protocol: TCP
      port: 4600
      targetPort: 4600
  type: LoadBalancer
