apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-doc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-doc
  template:
    metadata:
      labels:
        app: api-doc
    spec:
      containers:
      - name: api-doc
        image: r2553/aig-api-documentation:latest
        ports:
        - containerPort: 4400
        env:
         - name: HOST_URL
           value: http://localhost:9090

---

apiVersion: v1
kind: Service
metadata:
  name: api-doc-service
spec:
  selector:
    app: api-doc
  ports:
    - protocol: TCP
      port: 4400
      targetPort: 4400
  type: LoadBalancer
