apiVersion: apps/v1
kind: Deployment
metadata:
  name: aig-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aig-admin
  template:
    metadata:
      labels:
        app: aig-admin
    spec:
      imagePullSecrets: 
      - name: test-secret
      containers:
      - name: aig-admin
        image: 844605633964.dkr.ecr.af-south-1.amazonaws.com/aig-admin-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4500


---

apiVersion: v1
kind: Service
metadata:
  name: aig-admin-service
spec:
  selector:
    app: aig-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4500
  type: LoadBalancer
