apiVersion: apps/v1
kind: Deployment
metadata:
  name: aig-verification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aig-verification
  template:
    metadata:
      labels:
        app: aig-verification
    spec:
      containers:
      - name: aig-verification
        image: r2553/aig-verification-portal:latest
        ports:
        - containerPort: 4200


---

apiVersion: v1
kind: Service
metadata:
  name: aig-verification-service
spec:
  selector:
    app: aig-verification
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer
