apiVersion: apps/v1
kind: Deployment
metadata:
  name: aig-emergency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aig-emergency
  template:
    metadata:
      labels:
        app: aig-emergency
    spec:
      containers:
      - name: aig-emergency
        image: r2553/aig-emergency-portal:latest
        ports:
        - containerPort: 4300


---

apiVersion: v1
kind: Service
metadata:
  name: aig-emergency-service
spec:
  selector:
    app: aig-emergency
  ports:
    - protocol: TCP
      port: 4300
      targetPort: 4300
  type: LoadBalancer
